### ISSUE TITLE
Question: how to switch user

### ISSUE THREAD

**Issue by BMR731** [camdenfullmer/unsplash-swift#1]
you know some operation need the logged in user,for example the "like" operation,
i am user1, she is user2, so,when i request the "like" , i don't know which user use it,

so, without the login operation , how to do that operation which need logged-in user?

i can't find the login operation in unsplash API Doc,i don't know how to do this work.....thank you, sir

**Comment by camdenfullmer** [comment]
I don't think I'm understanding you're question correctly. Currently the SDK only allows for one user to be logged in at a time.
